apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark-apps
spec:
  type: Python
  #pythonVersion: "3" <- Optional
  mode: cluster
  image: mgarcia92/spark:v2
  imagePullPolicy: Always
  #mainClass: org.apache.spark.examples.SparkPi <- Just for Scala
  mainApplicationFile: "src/spark/layers/stage/stage.py" #"local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: git-repo
      gitRepo:
        repository: https://github.com/MarceloGarcia92/sentimentAnalisys.git
        revision: develop
        directory: .
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    volumeMounts:
      - name: git-repo
        mountPath: /opt/spark/work-dir
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    volumeMounts:
      - name: git-repo
        mountPath: /opt/spark/work-dir