apiVersion: v1
kind: Service
metadata:
  namespace: spark-app
  name: spark-master
spec:
  selector:
    app: spark-master
  ports:
  - name: web-ui
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: master-rest
    protocol: TCP
    port: 6066
    targetPort: 6066

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark-app
  name: spark-master
  labels:
    app: spark-master
spec:
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: mgarcia92/spark:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 6066
        command: ["/bin/bash", "/start-spark.sh"]
        env:
        - name: SPARK_WORKLOAD
          value: "master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: SPARK_WORKER_LOG
          value: "/opt/spark/logs/spark-master.out"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: spark-app
  name: spark-worker
  labels:
    app: spark-worker
spec:
  selector:
    matchLabels:
      name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: mgarcia92/spark:v1
        imagePullPolicy: Always
        env:
        - name: SPARK_WORKLOAD
          value: "worker"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        - name: SPARK_WORKER_LOG
          value: "/opt/spark/logs/spark-worker.out"
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
        command: ["/bin/bash", "/start-spark.sh"]
        ports:
        - containerPort: 8081