FROM python:3.8-slim-buster

ENV AIRFLOW_HOME /usr/local/airflow

RUN pip install --no-cache-dir apache-airflow

#EXPOSE 8080

#CMD ["airflow","airflow", "webserver", "--port", "8080"]
#CMD ["airflow","airflow", "webserver", "--port", "8080"]