apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spark-app
  name: spark-service
spec:
  ports:
    - port: 7077
      protocol: TCP
      targetPort: 7077
      nodePort: 30010
  selector:
    #type: ETL
    app: spark-app 
  type: NodePort
status:
  loadBalancer: {}
